### ISSUE TITLE
Cannot deploy contract to Mumbai Polygon testnet

### ISSUE THREAD

**Issue by lucianoacsilva** [fireblocks/hardhat-fireblocks#2]
Hello,

I am trying to deploy a contract at Mumbai Polygon testnet. However, it returns this error:

`TypeError: Cannot read properties of null (reading 'sendTransaction')
    at ContractFactory.<anonymous> (/Users/lucianocampagnoli/Documents/DAX/greener-hardhat/node_modules/@ethersproject/contracts/src.ts/index.ts:1247:38)
    at step (/Users/lucianocampagnoli/Documents/DAX/greener-hardhat/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/Users/lucianocampagnoli/Documents/DAX/greener-hardhat/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/Users/lucianocampagnoli/Documents/DAX/greener-hardhat/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`

I configured my hardhat.config.ts file as the README.md suggests:

```
import { HardhatUserConfig } from "hardhat/config";
import "@nomicfoundation/hardhat-toolbox";
import "@fireblocks/hardhat-fireblocks";
import * as dotenv from "dotenv";
import fs from "fs";
import path from "path";

dotenv.config();
const secretKey = fs.readFileSync(path.resolve(__dirname, "./fireblocks_secret.key"), "utf8");

const config: HardhatUserConfig = {
  solidity: "0.8.17",
  networks: {
    mumbai: {
      url: "https://rpc-mumbai.maticvigil.com",
      fireblocks: {
        privateKey: secretKey || "",
        apiKey: process.env.FIREBLOCKS_API_KEY || "",
        vaultAccountIds: process.env.FIREBLOCKS_VAULT_ACCOUNT_IDS,
      }
    }
  },
};

export default config;
```

Does anyone knows what could being done wrongly?

Best Regards

Luciano Augusto

**Comment by orenyomtov** [comment]
Hey, sorry for taking a long time to reply, is this issue still relevant?

**Comment by orenyomtov** [comment]
Hey, this should be working now.
Please open a new issue if the issue persists.
